import { useEffect,useMemo,useRef,useState } from "react"; import { Link } from "react-router"; import AppLayout from "../components/layout/AppLayout"; import { apiRequest } from "../lib/api"; import { useAuth } from "../context/useAuth";
type Team={id:string;name:string}; type Project={id:string;name:string;teamId:string}; type Task={id:string;title:string;projectId:string;assigneeId:string|null;column:{name:string};assignee:{name:string}|null}; type Activity={id:string;action:string;entity:string;projectId:string|null;createdAt:string;user:{id:string;name:string}}; type Summary={project:Project;teamName:string;dashboard:{totalTasks:number;completedTasks:number;totalComments:number}};
function initials(name:string){return name.split(" ").map(p=>p[0]).join("").slice(0,2).toUpperCase()} function ago(date:string){const m=Math.floor((Date.now()-new Date(date).getTime())/60000);return m<1?'Just now':m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`}
export default function DashboardPage(){const{user,currentOrganization}=useAuth();const[teams,setTeams]=useState<Team[]>([]);const[projects,setProjects]=useState<Project[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[activities,setActivities]=useState<Activity[]>([]);const[summaries,setSummaries]=useState<Summary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[momentumMenuOpen,setMomentumMenuOpen]=useState(false);const momentumMenuRef=useRef<HTMLDivElement>(null);const organizationId=currentOrganization?.organization.id;
useEffect(()=>{if(!organizationId)return;let active=true;async function load(){setLoading(true);try{const tr=await apiRequest(`/teams/organization/${organizationId}`);const ts=tr.data.teams as Team[];const prs=await Promise.all(ts.map(t=>apiRequest(`/projects/teams/${t.id}`)));const ps=prs.flatMap(r=>r.data.projects as Project[]);const [dr,tar,ar]=await Promise.all([Promise.all(ps.map(p=>apiRequest(`/dashboard/projects/${p.id}`))),Promise.all(ps.map(p=>apiRequest(`/tasks/projects/${p.id}`))),Promise.all(ps.map(p=>apiRequest(`/activities/projects/${p.id}`)))]);if(!active)return;setTeams(ts);setProjects(ps);setTasks(tar.flatMap(r=>r.data.tasks));setActivities(ar.flatMap(r=>r.data.activities).sort((a:Activity,b:Activity)=>+new Date(b.createdAt)-+new Date(a.createdAt)));setSummaries(ps.map((p,i)=>({project:p,teamName:ts.find(t=>t.id===p.teamId)?.name??'Team',dashboard:dr[i].data.dashboard})));}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[organizationId]);
useEffect(()=>{if(!momentumMenuOpen)return;function closeMenu(event:MouseEvent){if(!momentumMenuRef.current?.contains(event.target as Node))setMomentumMenuOpen(false)}function closeOnEscape(event:KeyboardEvent){if(event.key==='Escape')setMomentumMenuOpen(false)}document.addEventListener('mousedown',closeMenu);document.addEventListener('keydown',closeOnEscape);return()=>{document.removeEventListener('mousedown',closeMenu);document.removeEventListener('keydown',closeOnEscape)}},[momentumMenuOpen]);
const completed=tasks.filter(t=>t.column.name.toLowerCase()==='done').length;const inProgress=tasks.filter(t=>t.column.name.toLowerCase()==='in progress').length;const completion=tasks.length?Math.round(completed/tasks.length*100):0;const myTasks=useMemo(()=>tasks.filter(t=>t.assigneeId===user?.id).slice(0,5),[tasks,user]);const firstName=user?.name.split(' ')[0]??'there';
if(loading)return <AppLayout><div className="dashboard-loading"><i/><p>Preparing your workspace</p></div></AppLayout>;
return <AppLayout><div className="command-dashboard">
  <header className="dashboard-welcome"><div><div className="dashboard-kicker"><span/> LIVE WORKSPACE</div><h1>Good morning, {firstName}.</h1><p>Here’s the pulse of <b>{currentOrganization?.organization.name}</b> today.</p></div><div className="dashboard-date"><span>{new Date().toLocaleDateString(undefined,{weekday:'long'})}</span><b>{new Date().getDate()}</b><small>{new Date().toLocaleDateString(undefined,{month:'short',year:'numeric'})}</small></div></header>
  {error&&<div className="dashboard-error">{error}</div>}
  <section className="metric-grid"><article className="metric-card primary-metric"><div className="metric-head"><span>Overall progress</span><i>↗</i></div><div className="metric-value">{completion}<small>%</small></div><div className="metric-bar"><i style={{width:`${completion}%`}}/></div><p><b>+8%</b> from last week</p></article><article className="metric-card"><div className="metric-head"><span>Active tasks</span><i className="mint">✓</i></div><div className="metric-value">{tasks.length}</div><p><b>{inProgress}</b> currently in motion</p><div className="metric-spark"><i/><i/><i/><i/><i/><i/></div></article><article className="metric-card"><div className="metric-head"><span>Projects</span><i className="coral-bg">▦</i></div><div className="metric-value">{projects.length}</div><p>Across <b>{teams.length} teams</b></p><div className="metric-avatars"><span>PD</span><span>MK</span><span>OP</span><em>+{Math.max(0,projects.length-3)}</em></div></article><article className="metric-card"><div className="metric-head"><span>Completed</span><i className="gold-bg">★</i></div><div className="metric-value">{completed}</div><p><b>{completion}%</b> completion rate</p><div className="ring-chart" style={{'--progress':`${completion*3.6}deg`} as React.CSSProperties}><span>{completion}%</span></div></article></section>
  <section className="dashboard-grid"><article className="dash-panel focus-panel"><div className="panel-title"><div><span>MY FOCUS</span><h2>Priority tasks</h2></div><Link to="/my-tasks">View all <b>→</b></Link></div><div className="focus-list">{myTasks.length?myTasks.map((task,index)=><Link to="/my-tasks" key={task.id} className="focus-row"><button aria-label="Mark complete">{task.column.name.toLowerCase()==='done'?'✓':''}</button><div><b>{task.title}</b><span>{projects.find(p=>p.id===task.projectId)?.name??'Project'}</span></div><em className={index===0?'urgent':''}>{task.column.name}</em><i>•••</i></Link>):<div className="empty-dash">Your focus list is clear. Enjoy the space.</div>}</div></article>
  <article className="dash-panel momentum-panel"><div className="panel-title"><div><span>THIS WEEK</span><h2>Momentum</h2></div><div className="momentum-menu" ref={momentumMenuRef}><button type="button" aria-label="Open momentum actions" aria-haspopup="menu" aria-expanded={momentumMenuOpen} onClick={()=>setMomentumMenuOpen(open=>!open)}>•••</button>{momentumMenuOpen&&<div className="momentum-actions" role="menu"><p>Momentum actions</p><Link role="menuitem" to="/my-tasks" onClick={()=>setMomentumMenuOpen(false)}><span>✓</span><div><b>Review my tasks</b><small>See priorities and progress</small></div><i>→</i></Link><Link role="menuitem" to="/projects" onClick={()=>setMomentumMenuOpen(false)}><span>▦</span><div><b>View all projects</b><small>Explore project health</small></div><i>→</i></Link></div>}</div></div><div className="momentum-score"><strong>{completion}%</strong><p>Team velocity<br/><b>Trending upward ↗</b></p></div><div className="bar-chart">{[34,52,46,72,66,87,58].map((h,i)=><i key={i} style={{height:`${h}%`}} className={i===5?'active':''}><span>{['M','T','W','T','F','S','S'][i]}</span></i>)}</div></article>
  <article className="dash-panel projects-panel"><div className="panel-title"><div><span>PORTFOLIO</span><h2>Project health</h2></div><Link to="/projects">All projects <b>→</b></Link></div><div className="project-health">{summaries.slice(0,4).map((s,i)=>{const p=s.dashboard.totalTasks?Math.round(s.dashboard.completedTasks/s.dashboard.totalTasks*100):0;return <Link to={`/projects/${s.project.id}/board`} key={s.project.id}><span className={`project-mark mark-${i%4}`}>{s.project.name[0]}</span><div><b>{s.project.name}</b><small>{s.teamName} · {s.dashboard.totalTasks} tasks</small></div><em><i style={{width:`${p}%`}}/></em><strong>{p}%</strong></Link>})}</div></article>
  <article className="dash-panel activity-panel"><div className="panel-title"><div><span>LIVE FEED</span><h2>Recent activity</h2></div><i className="live-dot"/></div><div className="activity-feed">{activities.slice(0,5).map(a=><div key={a.id}><span>{initials(a.user.name)}</span><p><b>{a.user.id===user?.id?'You':a.user.name}</b> {a.action.toLowerCase()} a {a.entity.toLowerCase()}<small>{ago(a.createdAt)}</small></p></div>)}</div></article></section>
</div></AppLayout>}
