import { Link } from "react-router";

const features = [
  { number: "01", title: "Plan with clarity", text: "Turn ambitious ideas into focused projects, fluid boards, and tasks your team actually wants to use.", icon: "M4 6h16M4 12h10M4 18h7" },
  { number: "02", title: "Move as one", text: "Keep ownership, comments, decisions, and progress in one calm workspace—without status-meeting overload.", icon: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87" },
  { number: "03", title: "See the signal", text: "Live progress, workload, and activity give leaders the context to unblock work before it slows down.", icon: "M3 3v18h18M7 16l4-5 4 3 5-8" },
];

function Icon({ path }: { path: string }) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={path}/></svg>; }

export default function HomePage() {
  return <main className="landing-page">
    <nav className="landing-nav"><a href="#top" className="landing-logo"><span>F</span>FlowDeck</a><div className="landing-links"><a href="#product">Product</a><a href="#workflow">How it works</a><a href="#results">Results</a><a href="#about">About</a></div><div className="landing-actions"><Link to="/login" className="text-link">Sign in</Link><Link to="/register" className="landing-button landing-button-dark">Start free <span>↗</span></Link></div></nav>

    <section id="top" className="landing-hero"><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><div className="hero-copy"><div className="eyebrow"><span/> The modern work studio</div><h1>Make space for<br/><em>meaningful</em> work.</h1><p>FlowDeck brings projects, people, and momentum into one beautifully focused workspace—so your team can move from idea to impact.</p><div className="hero-actions"><Link to="/register" className="landing-button landing-button-accent">Build your workspace <span>→</span></Link><a href="#product" className="watch-link"><i>▶</i> See it in motion</a></div><div className="hero-proof"><div className="avatar-stack"><span>AK</span><span>MR</span><span>JS</span><span>+2k</span></div><p><b>4.9/5</b><br/>Loved by focused teams</p></div></div>

      <div className="hero-scene" aria-label="Animated FlowDeck workspace preview"><div className="scene-orbit orbit-one"/><div className="scene-orbit orbit-two"/><div className="scene-card scene-main"><div className="scene-top"><div><small>SPRINT 08</small><strong>Product launch</strong></div><span className="scene-avatar">LM</span></div><div className="scene-progress"><span><i style={{width:"72%"}}/></span><b>72%</b></div><div className="mini-board"><div><small>TO DO · 3</small><article><i className="dot coral"/>Research patterns<span>AK</span></article><article><i className="dot gold"/>Write launch copy<span>MR</span></article></div><div><small>IN PROGRESS · 2</small><article className="active-card"><i className="dot teal"/>Homepage motion<span>JS</span></article><article><i className="dot coral"/>QA workspace<span>LM</span></article></div></div></div><div className="scene-card scene-float scene-float-one"><i className="pulse-dot"/><div><small>PROJECT VELOCITY</small><strong>+28%</strong></div><svg viewBox="0 0 100 32"><path d="M0 25 C18 28 25 9 43 16 S68 24 100 3" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div className="scene-card scene-float scene-float-two"><div className="checkmark">✓</div><div><strong>12 tasks completed</strong><small>You're ahead of schedule</small></div></div></div>
    </section>

    <section id="product" className="landing-section"><div className="section-heading"><div><span className="section-index">01 / PRODUCT</span><h2>Everything your team needs.<br/><em>Nothing it doesn’t.</em></h2></div><p>Designed to feel effortless from day one, while powerful enough to run your most important work.</p></div><div className="feature-grid">{features.map(feature=><article className="feature-card" key={feature.number}><div className="feature-icon"><Icon path={feature.icon}/></div><span>{feature.number}</span><h3>{feature.title}</h3><p>{feature.text}</p><a href="#workflow">Explore feature <b>↗</b></a></article>)}</div></section>

    <section id="workflow" className="workflow-section"><div className="workflow-copy"><span className="section-index light">02 / HOW IT WORKS</span><h2>From scattered<br/>to <em>in sync.</em></h2><p>FlowDeck creates a shared rhythm for your team. Set direction, make progress visible, and let everyone do their best work.</p><Link to="/register" className="landing-button landing-button-light">Try the workflow <span>→</span></Link></div><div className="workflow-steps">{[["01","Create your space","Shape a workspace around how your team actually works."],["02","Bring work into focus","Turn priorities into clear projects, owners, and next steps."],["03","Build momentum","Collaborate in context and watch progress compound."]].map((step,index)=><article key={step[0]}><span>{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div><i className={index===0?"active":""}>→</i></article>)}</div></section>

    <section id="results" className="results-section"><p>Trusted by teams who care about the work</p><div className="logo-row"><span>Northstar</span><span>VERDANT</span><span>Foundry</span><span>ARC / STUDIO</span><span>Monument</span></div><div className="result-card"><blockquote>“FlowDeck gave us back the headspace to think. The team is aligned, the work is moving, and nothing important gets buried.”</blockquote><div><span className="quote-avatar">SL</span><p><b>Sofia Lin</b><br/>VP Product, Northstar</p></div><strong>38%<small>fewer status meetings</small></strong></div></section>

    <section id="about" className="final-cta"><div><span className="section-index">READY WHEN YOU ARE</span><h2>Your best work<br/>starts with <em>space.</em></h2></div><div><p>Create a calmer, clearer way to move work forward. Your first workspace is free.</p><Link to="/register" className="landing-button landing-button-accent">Start building today <span>→</span></Link></div></section>
    <footer><a href="#top" className="landing-logo"><span>F</span>FlowDeck</a><p>Organize. Collaborate. Deliver.</p><div><a href="#product">Product</a><Link to="/login">Sign in</Link><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
